{
 "title": "Smoke Ping",
 "description": "Smoke Ping using https://github.com/SuperQ/smokeping_prober\r\nwith \r\nlatency heatmap\r\nlatency graph\r\npacket loss gragh\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "query": "label_values(smokeping_response_duration_seconds_bucket, host)"
   },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Smokeping $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Smoke Ping - $target",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (rate(smokeping_response_duration_seconds_bucket{host=\"$target\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Packet Loss - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(smokeping_requests_total{host=\"$target\",instance=\"$instance\"} - smokeping_response_duration_seconds_count{host=\"$target\",instance=\"$instance\"})/smokeping_requests_total{host=\"$target\",instance=\"$instance\"} ",
     "legendFormat": "Percentage"
    },
    {
     "expr": "(smokeping_requests_total{host=\"$target\",instance=\"$instance\"} - smokeping_response_duration_seconds_count{host=\"$target\",instance=\"$instance\"})",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Latency - $target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "smokeping_response_duration_seconds_sum{host=\"$target\",instance=\"$instance\"} / smokeping_response_duration_seconds_count{host=\"$target\",instance=\"$instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}